name: Veriviz CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cd-frontend:
    name: "Continuous Deployment - Veriviz"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger OKD Build for Veriviz
        run: |
          curl -X POST ${{ secrets.CD_BUILD_WEBHOOK_FRONTEND}}
  cd-backend:
    name: "Continuous Deployment - Backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger OKD Build for Veriviz Backend
        run: |
          curl -X POST ${{ secrets.CD_BUILD_WEBHOOK_VERIVIZ_BACKEND }}
